/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/admin/images/{id}/review": {
    /**
     * Review image
     * @description Approve or reject an image (Admin only)
     */
    post: {
      parameters: {
        path: {
          /** @description Image ID */
          id: string;
        };
      };
      /** @description Review Request */
      requestBody: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/admin/images/pending": {
    /**
     * List pending images
     * @description List images waiting for moderation (Admin only)
     */
    get: {
      parameters: {
        query?: {
          /** @description Limit */
          limit?: number;
          /** @description Offset */
          offset?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/admin/opportunities/{id}": {
    /**
     * Update opportunity (Admin)
     * @description Update any opportunity (Admin only)
     */
    put: {
      parameters: {
        path: {
          /** @description Opportunity ID */
          id: string;
        };
      };
      requestBody: components["requestBodies"]["domain.Opportunity"];
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Delete opportunity (Admin)
     * @description Delete any opportunity (Admin only)
     */
    delete: {
      parameters: {
        path: {
          /** @description Opportunity ID */
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/admin/reviews": {
    /**
     * List Reviews (Admin)
     * @description List all reviews (Admin only)
     */
    get: {
      parameters: {
        query?: {
          /** @description Limit */
          limit?: number;
          /** @description Offset */
          offset?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/admin/reviews/{id}": {
    /**
     * Delete Review (Admin)
     * @description Delete a review by ID (Admin only)
     */
    delete: {
      parameters: {
        path: {
          /** @description Review ID */
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/admin/stats": {
    /**
     * Get system stats
     * @description Get system statistics (Admin only)
     */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/admin/users": {
    /**
     * List users (Admin)
     * @description List users with role filter (Admin only)
     */
    get: {
      parameters: {
        query?: {
          /** @description Limit */
          limit?: number;
          /** @description Offset */
          offset?: number;
          /** @description Role */
          role?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/admin/users/{id}/status": {
    /**
     * Update user status (Admin)
     * @description Update user status (e.g. suspend) (Admin only)
     */
    put: {
      parameters: {
        path: {
          /** @description User ID */
          id: string;
        };
      };
      requestBody: components["requestBodies"]["Request"];
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/applications": {
    /**
     * List applications
     * @description List applications with filters
     */
    get: {
      parameters: {
        query?: {
          /** @description Limit */
          limit?: number;
          /** @description Offset */
          offset?: number;
          /** @description Status */
          status?: string;
          /** @description Opportunity ID */
          opportunityId?: string;
          /** @description Host ID */
          hostId?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Create application
     * @description Create a new application for an opportunity
     */
    post: {
      /** @description Application Request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["domain.Application"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["domain.Application"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/applications/{id}": {
    /**
     * Get application by ID
     * @description Get detailed information of an application
     */
    get: {
      parameters: {
        path: {
          /** @description Application ID */
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["domain.Application"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Delete application
     * @description Delete an application (Owner only)
     */
    delete: {
      parameters: {
        path: {
          /** @description Application ID */
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/applications/{id}/status": {
    /**
     * Update application status
     * @description Update status of an application (Host/User)
     */
    put: {
      parameters: {
        path: {
          /** @description Application ID */
          id: string;
        };
      };
      requestBody: components["requestBodies"]["Request"];
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/login": {
    /**
     * Login user
     * @description Login with email/password or OAuth token
     */
    post: {
      /** @description Login Request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["api.LoginRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/logout": {
    /**
     * Logout user
     * @description Logout the current user
     */
    post: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/register": {
    /**
     * Register a new user
     * @description Register a new user with name, email and password
     */
    post: {
      /** @description Register Request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["api.RegisterRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["domain.User"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Conflict */
        409: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/hosts": {
    /**
     * Create host profile
     * @description Create a new host profile for the current user
     */
    post: {
      requestBody: components["requestBodies"]["domain.Host"];
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["domain.Host"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/hosts/me": {
    /**
     * Get current host profile
     * @description Get host profile for the current user
     */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["domain.Host"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Update host profile
     * @description Update host profile for the current user
     */
    put: {
      requestBody: components["requestBodies"]["domain.Host"];
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/images": {
    /**
     * Upload image
     * @description Upload an image file
     */
    post: {
      requestBody: {
        content: {
          "multipart/form-data": {
            /**
             * Format: binary
             * @description Image File
             */
            image: string;
          };
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["domain.Image"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/images/{id}/status": {
    /**
     * Update image status
     * @description Update image status (Admin only)
     */
    put: {
      parameters: {
        path: {
          /** @description Image ID */
          id: string;
        };
      };
      requestBody: components["requestBodies"]["Request"];
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/images/private/{id}": {
    /**
     * Get private image
     * @description Get private image content (Owner/Admin)
     */
    get: {
      parameters: {
        path: {
          /** @description Image ID */
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "image/jpeg": string;
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "image/jpeg": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/opportunities": {
    /**
     * List opportunities
     * @description List opportunities with pagination and filters
     */
    get: {
      parameters: {
        query?: {
          /** @description Limit */
          limit?: number;
          /** @description Offset */
          offset?: number;
          /** @description Host ID */
          hostId?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["domain.Opportunity"][];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Create opportunity
     * @description Create a new opportunity (Host only)
     */
    post: {
      requestBody: components["requestBodies"]["domain.Opportunity"];
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["domain.Opportunity"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/opportunities/{id}": {
    /**
     * Get opportunity by ID
     * @description Get detailed information of an opportunity
     */
    get: {
      parameters: {
        path: {
          /** @description Opportunity ID */
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["domain.Opportunity"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Update opportunity
     * @description Update an existing opportunity (Host only)
     */
    put: {
      parameters: {
        path: {
          /** @description Opportunity ID */
          id: string;
        };
      };
      requestBody: components["requestBodies"]["domain.Opportunity"];
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Delete opportunity
     * @description Delete an opportunity (Host only)
     */
    delete: {
      parameters: {
        path: {
          /** @description Opportunity ID */
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/opportunities/{id}/bookmark": {
    /**
     * Add bookmark
     * @description Add an opportunity to bookmarks
     */
    post: {
      parameters: {
        path: {
          /** @description Opportunity ID */
          id: string;
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Conflict */
        409: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Remove bookmark
     * @description Remove an opportunity from bookmarks
     */
    delete: {
      parameters: {
        path: {
          /** @description Opportunity ID */
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/opportunities/{id}/reviews": {
    /**
     * List reviews by opportunity
     * @description Get all reviews for a specific opportunity
     */
    get: {
      parameters: {
        path: {
          /** @description Opportunity ID */
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["service.ReviewWithUser"][];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Create review
     * @description Create a new review for an opportunity
     */
    post: {
      parameters: {
        path: {
          /** @description Opportunity ID */
          id: string;
        };
      };
      /** @description Review Request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["service.CreateReviewRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["domain.Review"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/opportunities/search": {
    /**
     * Search opportunities
     * @description Search opportunities by various criteria
     */
    get: {
      parameters: {
        query?: {
          /** @description Keyword */
          q?: string;
          /** @description Type */
          type?: string;
          /** @description City */
          city?: string;
          /** @description Country */
          country?: string;
          /** @description Start Date */
          startDate?: string;
          /** @description End Date */
          endDate?: string;
          /** @description Latitude */
          lat?: number;
          /** @description Longitude */
          lng?: number;
          /** @description Distance (km) */
          distance?: number;
          /** @description Limit */
          limit?: number;
          /** @description Offset */
          offset?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/user/me": {
    /**
     * Get current user
     * @description Get profile information for the current user
     */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["domain.User"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Update current user
     * @description Update profile information for the current user
     */
    put: {
      /** @description Update User Request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["api.UpdateUserRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["domain.User"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/users": {
    /**
     * Get all users
     * @description Get a list of all users (Admin only)
     */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["domain.User"][];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/users/{id}": {
    /**
     * Get user by ID
     * @description Get user details by ID (Admin only)
     */
    get: {
      parameters: {
        path: {
          /** @description User ID */
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["domain.User"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/users/me/bookmarks": {
    /**
     * List bookmarks
     * @description List bookmarked opportunities
     */
    get: {
      parameters: {
        query?: {
          /** @description Limit */
          limit?: number;
          /** @description Offset */
          offset?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/users/me/notifications": {
    /**
     * List notifications
     * @description List notifications for current user
     */
    get: {
      parameters: {
        query?: {
          /** @description Limit */
          limit?: number;
          /** @description Offset */
          offset?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/users/me/notifications/{id}/read": {
    /**
     * Mark notification as read
     * @description Mark a specific notification as read
     */
    put: {
      parameters: {
        path: {
          /** @description Notification ID */
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
  "/users/me/notifications/read-all": {
    /**
     * Mark all notifications as read
     * @description Mark all notifications as read for current user
     */
    put: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["api.ErrorResponse"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    "api.ErrorResponse": {
      error?: string;
    };
    "api.LoginRequest": {
      email: string;
      /** @enum {string} */
      loginType: "password" | "google" | "apple";
      /** @description 密碼登入時為必需 */
      password?: string;
      /** @description OAuth 登入時為必需 */
      token?: string;
    };
    "api.RegisterRequest": {
      email: string;
      name: string;
      password: string;
    };
    "api.UpdateUserRequest": {
      accommodationNeeds?: string;
      address?: string;
      avatar?: string;
      bio?: string;
      birthDate?: string;
      culturalInterests?: string[];
      emergencyContact?: components["schemas"]["domain.EmergencyContact"];
      languages?: string[];
      learningGoals?: string[];
      location?: components["schemas"]["domain.Location"];
      name?: string;
      personalInfo?: components["schemas"]["domain.PersonalInfo"];
      phoneNumber?: string;
      physicalCondition?: string;
      preferredWorkHours?: number;
      skills?: string[];
      socialMedia?: components["schemas"]["domain.SocialMedia"];
      workExchangePreferences?: components["schemas"]["domain.WorkExchangePreferences"];
      workExperience?: components["schemas"]["domain.WorkExperience"][];
    };
    "domain.AdditionalMedia": {
      presentation?: components["schemas"]["domain.HostPhoto"];
      virtualTour?: string;
    };
    "domain.Amenities": {
      accommodation?: {
        [key: string]: boolean;
      };
      activities?: {
        [key: string]: boolean;
      };
      amenitiesNotes?: string;
      basics?: {
        [key: string]: boolean;
      };
      customAmenities?: string[];
      lifestyle?: {
        [key: string]: boolean;
      };
      workExchange?: {
        [key: string]: boolean;
      };
      workExchangeDescription?: string;
    };
    "domain.Application": {
      applicationDetails?: components["schemas"]["domain.ApplicationDetails"];
      createdAt?: string;
      hostId?: string;
      id?: string;
      opportunityId?: string;
      reviewDetails?: components["schemas"]["domain.ReviewDetails"];
      status?: components["schemas"]["domain.ApplicationStatus"];
      statusNote?: string;
      updatedAt?: string;
      userId?: string;
    };
    "domain.ApplicationDetails": {
      /** @description Days */
      duration?: number;
      /** @description YYYY-MM-DD */
      endDate?: string;
      languages?: string[];
      message?: string;
      relevantExperience?: string;
      /** @description YYYY-MM-DD */
      startDate?: string;
      travelingWith?: {
        children?: boolean;
        partner?: boolean;
        pets?: boolean;
      };
    };
    "domain.ApplicationProcess": {
      currentApplications?: number;
      deadline?: string;
      instructions?: string;
      maxApplications?: number;
      questions?: string[];
    };
    /** @enum {string} */
    "domain.ApplicationStatus": "DRAFT" | "PENDING" | "ACCEPTED" | "REJECTED" | "CANCELLED";
    "domain.Benefits": {
      accommodation?: {
        description?: string;
        provided?: boolean;
        /** @description private_room, shared_room, etc. */
        type?: string;
      };
      meals?: {
        count?: number;
        description?: string;
        provided?: boolean;
      };
      otherBenefits?: string[];
      stipend?: {
        amount?: number;
        currency?: string;
        /** @description daily, weekly, monthly */
        frequency?: string;
        provided?: boolean;
      };
    };
    "domain.CapacityOverride": {
      capacity?: number;
      endDate?: string;
      startDate?: string;
    };
    "domain.ContactInfo": {
      contactEmail?: string;
      contactHours?: string;
      contactMobile?: string;
      notes?: string;
      phone?: string;
      socialMedia?: components["schemas"]["domain.HostSocialMedia"];
      website?: string;
    };
    "domain.EmergencyContact": {
      email?: string;
      name?: string;
      phone?: string;
      relationship?: string;
    };
    "domain.GeoJSON": {
      coordinates: number[];
      type: string;
    };
    "domain.Host": {
      additionalMedia?: components["schemas"]["domain.AdditionalMedia"];
      amenities?: components["schemas"]["domain.Amenities"];
      category?: string;
      contactInfo?: components["schemas"]["domain.ContactInfo"];
      createdAt?: string;
      description?: string;
      details?: components["schemas"]["domain.HostDetails"];
      email?: string;
      features?: components["schemas"]["domain.HostFeatures"];
      id?: string;
      location?: components["schemas"]["domain.HostLocation"];
      mobile?: string;
      name?: string;
      organizationId?: string;
      photoDescriptions?: string[];
      photos?: components["schemas"]["domain.HostPhoto"][];
      ratings?: components["schemas"]["domain.HostRatings"];
      slug?: string;
      status?: components["schemas"]["domain.HostStatus"];
      statusHistory?: components["schemas"]["domain.HostStatusHistory"][];
      statusNote?: string;
      type?: components["schemas"]["domain.HostType"];
      updatedAt?: string;
      userId?: string;
      verified?: boolean;
      verifiedAt?: string;
      videoIntroduction?: components["schemas"]["domain.VideoIntroduction"];
    };
    "domain.HostDetails": {
      acceptsChildren?: boolean;
      acceptsCouples?: boolean;
      acceptsPets?: boolean;
      dietaryOptions?: string[];
      expectations?: string[];
      foundingYear?: number;
      languages?: string[];
      maxStayDuration?: number;
      minStayDuration?: number;
      providesAccommodation?: boolean;
      providesMeals?: boolean;
      rules?: string[];
      teamSize?: number;
      workDaysPerWeek?: number;
      workHoursPerWeek?: number;
    };
    "domain.HostFeatures": {
      environment?: {
        accessibility?: string;
        nearbyAttractions?: string[];
        surroundings?: string;
      };
      experience?: string;
      features?: string[];
      story?: string;
    };
    "domain.HostLocation": {
      address?: string;
      city?: string;
      coordinates: components["schemas"]["domain.GeoJSON"];
      country?: string;
      district?: string;
      showExactLocation?: boolean;
      zipCode?: string;
    };
    "domain.HostPhoto": {
      originalUrl?: string;
      previewUrl?: string;
      publicId?: string;
      secureUrl?: string;
      thumbnailUrl?: string;
    };
    "domain.HostRatings": {
      accommodation?: number;
      food?: number;
      hostHospitality?: number;
      learningOpportunities?: number;
      overall?: number;
      reviewCount?: number;
      workEnvironment?: number;
    };
    "domain.HostSocialMedia": {
      facebook?: string;
      instagram?: string;
      line?: string;
      linkedin?: string;
      other?: {
          name?: string;
          url?: string;
        }[];
      threads?: string;
      tiktok?: string;
      twitter?: string;
      youtube?: string;
    };
    /** @enum {string} */
    "domain.HostStatus": "PENDING" | "ACTIVE" | "INACTIVE" | "REJECTED" | "SUSPENDED" | "EDITING";
    "domain.HostStatusHistory": {
      status?: components["schemas"]["domain.HostStatus"];
      statusNote?: string;
      updatedAt?: string;
      updatedBy?: string;
    };
    /** @enum {string} */
    "domain.HostType": "FARM" | "HOSTEL" | "HOMESTAY" | "ECO_VILLAGE" | "RETREAT_CENTER" | "COMMUNITY" | "NGO" | "SCHOOL" | "CAFE" | "RESTAURANT" | "ART_CENTER" | "ANIMAL_SHELTER" | "OUTDOOR_ACTIVITY" | "OTHER" | "COWORKING_SPACE" | "CULTURAL_VENUE" | "COMMUNITY_CENTER";
    "domain.Image": {
      createdAt?: string;
      /** @description GCS 中的檔案路徑 (object name) */
      gcsPath?: string;
      id?: string;
      /** @description 透過 ImageKit 或 GCS 公開的 URL */
      publicUrl?: string;
      status?: components["schemas"]["domain.ImageStatus"];
      updatedAt?: string;
      userId?: string;
      visionData?: components["schemas"]["domain.VisionAIRawData"];
    };
    /** @enum {string} */
    "domain.ImageStatus": "PENDING" | "APPROVED" | "REJECTED";
    "domain.Impact": {
      culturalExchange?: string;
      environmentalContribution?: string;
      socialContribution?: string;
      sustainableDevelopmentGoals?: string[];
    };
    "domain.Location": {
      coordinates?: number[];
      /** @description "Point" */
      type?: string;
    };
    "domain.MonthlyCapacity": {
      bookedCount?: number;
      capacity?: number;
      /** @description YYYY-MM */
      month?: string;
    };
    "domain.Opportunity": {
      applicationProcess?: components["schemas"]["domain.ApplicationProcess"];
      benefits?: components["schemas"]["domain.Benefits"];
      createdAt?: string;
      description?: string;
      hasTimeSlots?: boolean;
      hostId?: string;
      id?: string;
      impact?: components["schemas"]["domain.Impact"];
      location?: components["schemas"]["domain.OpportunityLocation"];
      media?: components["schemas"]["domain.OpportunityMedia"];
      publicId?: string;
      /** @description Reusing HostRatings as structure is same */
      ratings?: components["schemas"]["domain.HostRatings"];
      requirements?: components["schemas"]["domain.Requirements"];
      shortDescription?: string;
      slug?: string;
      stats?: components["schemas"]["domain.OpportunityStats"];
      status?: components["schemas"]["domain.OpportunityStatus"];
      statusHistory?: components["schemas"]["domain.OpportunityStatusHistory"][];
      statusNote?: string;
      timeSlots?: components["schemas"]["domain.TimeSlot"][];
      title?: string;
      type?: components["schemas"]["domain.OpportunityType"];
      updatedAt?: string;
      workDetails?: components["schemas"]["domain.WorkDetails"];
    };
    "domain.OpportunityLocation": {
      address?: string;
      city?: string;
      coordinates: components["schemas"]["domain.GeoJSON"];
      country?: string;
      district?: string;
    };
    "domain.OpportunityMedia": {
      coverImage?: components["schemas"]["domain.HostPhoto"];
      descriptions?: string[];
      images?: components["schemas"]["domain.HostPhoto"][];
      videoDescription?: string;
      videoUrl?: string;
      virtualTour?: string;
    };
    "domain.OpportunityStats": {
      applications?: number;
      bookmarks?: number;
      shares?: number;
      views?: number;
    };
    /** @enum {string} */
    "domain.OpportunityStatus": "DRAFT" | "PENDING" | "ACTIVE" | "PAUSED" | "EXPIRED" | "FILLED" | "REJECTED" | "ADMIN_PAUSED" | "DELETED";
    "domain.OpportunityStatusHistory": {
      changedAt?: string;
      changedBy?: string;
      reason?: string;
      status?: components["schemas"]["domain.OpportunityStatus"];
    };
    /** @enum {string} */
    "domain.OpportunityType": "FARMING" | "GARDENING" | "ANIMAL_CARE" | "CONSTRUCTION" | "HOSPITALITY" | "COOKING" | "CLEANING" | "CHILDCARE" | "ELDERLY_CARE" | "TEACHING" | "LANGUAGE_EXCHANGE" | "CREATIVE" | "DIGITAL_NOMAD" | "ADMINISTRATION" | "MAINTENANCE" | "TOURISM" | "CONSERVATION" | "COMMUNITY" | "EVENT" | "OTHER";
    "domain.Other": {
      name?: string;
      url?: string;
    };
    "domain.PersonalInfo": {
      birthdate?: string;
      currentLocation?: string;
      education?: string;
      gender?: string;
      nationality?: string;
      occupation?: string;
    };
    /** @enum {string} */
    "domain.PrivacyLevel": "PUBLIC" | "REGISTERED" | "PRIVATE";
    "domain.PrivacySettings": {
      bio?: components["schemas"]["domain.PrivacyLevel"];
      email?: components["schemas"]["domain.PrivacyLevel"];
      languages?: components["schemas"]["domain.PrivacyLevel"];
      personalInfo?: components["schemas"]["domain.PrivacyLevel"];
      phone?: components["schemas"]["domain.PrivacyLevel"];
      skills?: components["schemas"]["domain.PrivacyLevel"];
      socialMedia?: components["schemas"]["domain.PrivacyLevel"];
      workExchangePreferences?: components["schemas"]["domain.PrivacyLevel"];
    };
    "domain.Profile": {
      accommodationNeeds?: string;
      address?: string;
      avatar?: string;
      bio?: string;
      birthDate?: string;
      culturalInterests?: string[];
      emergencyContact?: components["schemas"]["domain.EmergencyContact"];
      isPhoneVerified?: boolean;
      languages?: string[];
      learningGoals?: string[];
      location?: components["schemas"]["domain.Location"];
      personalInfo?: components["schemas"]["domain.PersonalInfo"];
      phoneNumber?: string;
      physicalCondition?: string;
      preferredWorkHours?: number;
      skills?: string[];
      socialMedia?: components["schemas"]["domain.SocialMedia"];
      workExchangePreferences?: components["schemas"]["domain.WorkExchangePreferences"];
      workExperience?: components["schemas"]["domain.WorkExperience"][];
    };
    "domain.Requirements": {
      acceptsCouples?: boolean;
      acceptsFamilies?: boolean;
      acceptsPets?: boolean;
      drivingLicense?: {
        carRequired?: boolean;
        motorcycleRequired?: boolean;
        otherDescription?: string;
        otherRequired?: boolean;
      };
      /** @description any, male, female */
      gender?: string;
      maxAge?: number;
      minAge?: number;
      otherRequirements?: string[];
      specificNationalities?: string[];
      specificSkills?: string[];
    };
    "domain.Review": {
      content: string;
      createdAt?: string;
      id?: string;
      opportunityId: string;
      rating: number;
      updatedAt?: string;
      /** @description The user who wrote the review */
      userId?: string;
    };
    "domain.ReviewDetails": {
      notes?: string;
      rating?: number;
      reviewedAt?: string;
      reviewedBy?: string;
    };
    "domain.SocialMedia": {
      facebook?: string;
      instagram?: string;
      linkedin?: string;
      other?: components["schemas"]["domain.Other"][];
      threads?: string;
      tiktok?: string;
      twitter?: string;
      website?: string;
      youtube?: string;
    };
    "domain.TimeSlot": {
      appliedCount?: number;
      capacityOverrides?: components["schemas"]["domain.CapacityOverride"][];
      confirmedCount?: number;
      defaultCapacity?: number;
      description?: string;
      /** @description YYYY-MM-DD */
      endDate?: string;
      id?: string;
      minimumStay?: number;
      monthlyCapacities?: components["schemas"]["domain.MonthlyCapacity"][];
      /** @description YYYY-MM-DD */
      startDate?: string;
      status?: components["schemas"]["domain.TimeSlotStatus"];
      workDaysPerWeek?: number;
      workHoursPerDay?: number;
    };
    /** @enum {string} */
    "domain.TimeSlotStatus": "OPEN" | "FILLED" | "CLOSED";
    "domain.User": {
      createdAt?: string;
      email?: string;
      emailVerified?: string;
      hostId?: string;
      id?: string;
      image?: string;
      name?: string;
      organizationId?: string;
      privacySettings?: components["schemas"]["domain.PrivacySettings"];
      profile?: components["schemas"]["domain.Profile"];
      role?: components["schemas"]["domain.UserRole"];
      status?: components["schemas"]["domain.UserStatus"];
      updatedAt?: string;
    };
    /** @enum {string} */
    "domain.UserRole": "USER" | "HOST" | "ADMIN";
    /** @enum {string} */
    "domain.UserStatus": "ACTIVE" | "SUSPENDED";
    "domain.VideoIntroduction": {
      description?: string;
      url?: string;
    };
    "domain.VisionAIRawData": {
      adult?: string;
      medical?: string;
      racy?: string;
      spoof?: string;
      violence?: string;
    };
    "domain.WorkDetails": {
      availableMonths?: number[];
      languages?: string[];
      learningOpportunities?: string[];
      /** @description low, medium, high */
      physicalDemand?: string;
      skills?: string[];
      tasks?: string[];
    };
    "domain.WorkExchangePreferences": {
      availableFrom?: string;
      availableTo?: string;
      dietaryRestrictions?: string[];
      hasDriverLicense?: boolean;
      maxDuration?: number;
      minDuration?: number;
      notes?: string;
      preferredLocations?: string[];
      preferredWorkTypes?: string[];
      specialNeeds?: string;
    };
    "domain.WorkExperience": {
      description?: string;
      duration?: string;
      title?: string;
    };
    "service.CreateReviewRequest": {
      content: string;
      opportunityId: string;
      rating: number;
    };
    "service.ReviewWithUser": {
      content: string;
      createdAt?: string;
      id?: string;
      opportunityId: string;
      rating: number;
      updatedAt?: string;
      user?: components["schemas"]["domain.User"];
      /** @description The user who wrote the review */
      userId?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: {
    /** @description Status Update Request */
    Request: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    /** @description Host Request */
    "domain.Host": {
      content: {
        "application/json": components["schemas"]["domain.Host"];
      };
    };
    /** @description Opportunity Request */
    "domain.Opportunity": {
      content: {
        "application/json": components["schemas"]["domain.Opportunity"];
      };
    };
  };
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
