name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Create .env.test file
      run: |
        echo "MONGODB_URI=mongodb://localhost:27017/taiwanstay_test" > .env.test
        echo "ENABLE_AUTH=false" >> .env.test
        echo "SUPPRESS_JEST_WARNINGS=true" >> .env.test

    - name: Run tests
      run: npm run test:ci
      env:
        NODE_OPTIONS: --max-old-space-size=4096
        FORCE_COLOR: true

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/
        fail_ci_if_error: false